version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: tutorial_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: tutorial
    ports:
      - "5432:5432"
    volumes:
      - tutorial_postgres_data:/var/lib/postgresql/data

volumes:
  tutorial_postgres_data:
